services:
  web:
    build: .
    container_name: vitazgio-site
    network_mode: host
    environment:
      - VITAZGIO_SESSION_SECRET=${VITAZGIO_SESSION_SECRET}
      - SSH_GATE_PASSWORD_PREFIX=${SSH_GATE_PASSWORD_PREFIX}
    volumes:
      - .:/app
    restart: unless-stopped

  guacd:
    image: guacamole/guacd
    container_name: guacd
    network_mode: host
    restart: unless-stopped
