services:
  web:
    build: .
    container_name: vitazgio-site
    network_mode: host
    env_file: .env
    volumes:
      - .:/app
    restart: unless-stopped

  guacd:
    image: guacamole/guacd
    container_name: guacd
    network_mode: host
    restart: unless-stopped
